version: '3.8'
services:
    app:
        build: ./
        container_name: 'node-app'
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./src:/app
        ports:
            - '${HTTP_PORT:-8080}:80'
    mongodb:
        image: mongo
        container_name: 'node-mongodb'
        restart: unless-stopped
        working_dir: /app
        volumes:
            - 'node-mongodb:/data/db'
        ports:
            - '${MONGO_PORT:-27017}:27017'

volumes:
    node-mongodb:
        name: node-mongodb
        driver: local